version: '3.8'
services:
  mysqlserver:
    image: mysql:8.0.23
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3308:3306
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_USER_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    cap_add:
      - SYS_NICE
 
  veralink:
    depends_on:
      - mysqlserver
    env_file: ./.env
    build:
      context: .
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
    	  "spring.datasource.url"  : "jdbc:mysql://mysqlserver:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_USER_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"


volumes:
  mysql_data:
  mysql_config:

